### PR TITLE
Fix your build yo!

### PR DESCRIPTION
**Pull request by UncleClapton**
* fix ESLint configs and fix missing dependencies.
* Add eslint ignore file which unignores (yes) dotfiles and ignores compiled files. This is mainly to filter out these files from a global lint
* Update several dev dependencies
    * normal deps have been left untouched.
* add `.nvmrc`. This is mainly to ease development for myself or anyone else who comes along wishing to contribute. 
    * This is also the proper way of defining which version of node to use in CI, since the node version string in `package.json` may be a range. `.nvmrc` OTTH MUST be resolvable to a single version of node.js
* Update CI config to ensure CI checks `.mjs` and `.cjs` files properly.
* Pull changes from beta branch to bring them back into sync.
* Fix numerous ESLint errors.
* Rescue revision endpoints now throw a `NotImplementedAPIError` since their implementation was never completed.
* update node to 16.4.0. This version is already sitting on Emmental

### CODE REVIEW

**Comment by UncleClapton** [comment]
85 lint errors, 64 warns. The majority seems to be about unused imports, badly ordered imports, or missing JSDoc blocks. I could commit fixes to these, but perhaps we should merge back the changes made directly to `beta` first so we get the two branches in line again? Thoughts @xlexi?

**Comment by xlexi** [comment]
Seems like a good idea

**Comment by UncleClapton** [comment]
👍 I'll start work on it tomorrow

**Comment by UncleClapton** [comment]
> Tomorrow
he said

> 11 days later

**Review by xlexi — APPROVED** [review]
LGTM

**Pull request merged**
