### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Peter253545**
Fixes users without `rats.write` being unable to change their display rat due to their rat ids being compared with `undefined` and not the new id.
Fixes "CMDR" not correctly being forbidden in names due to it being in uppercase.

### CODE REVIEW

**Comment by Peter253545** [comment]
Resolves FRH-2039 (I think, I don't have permission to view it)

**Comment by UncleClapton** [comment]
hey @SuperManifolds you may remember better than I about the details of some of the updates made here. perhaps we could get this one in?

**Comment by SuperManifolds** [comment]
This looks mostly good however I don't understand the change made to the oauth clients permission check

**Review by SuperManifolds — APPROVED** [review]
LGTM

**Pull request merged**
