### PR TITLE
API-328/Allow admins to force a hard delete rather than a soft delete by providing an HTTP header

### PR DESCRIPTION
**Pull request by xlexi**

### CODE REVIEW

**Comment by UncleClapton** [comment]
perhaps maybe we should employ some further protections like requiring the request to come with the user's password.

**Comment by xlexi** [comment]
Could do... Do you feel that is necessary?
The reasonable way to implement that I think is using Basic Auth header with the request.

**Comment by UncleClapton** [comment]
I'm kinda following how sites like GitHub and JIRA handle potentially destructive actions. In both cases they require some form of assurance that the user is who they are at the time the action is made. In Jira's case it's the temporary elevated user status, but the idea is the same.

Requiring a password would also emphasize the importance and severity of the action being taken. You can easily press through confirmation screens all day but being presented with an input box forces you to think a little more.

Admittedly in the age of password managers this wouldn't provide much more protection, but my reasoning is twofold here.

**Comment by xlexi** [comment]
What about doing something more githubby like just requiring the user to type "DELETE" into a text box?

**Comment by UncleClapton** [comment]
There's still a password beyond that typically :P

**Comment by xlexi** [comment]
No there isn't? at least not for repository deletions, they just make you type something into a box

**Comment by xlexi** [comment]
But if you prefer we do it password like, you alright with doing it as email and password in basic auth then?

**Comment by UncleClapton** [comment]
yea thats fine.

**Pull request merged**
